Created User crud api 작성
dbwls314/fastAPI_assign pull request #1
Opened 2022-01-06 08:33 UTC by dbwls314

### Summary

- 요약
 : models, User crud 작성

### Story

- 무엇에 대한 것인지
  - models : user, account, trash 테이블 생성
  - main : user crud 작성
  - 
### Changes

- 어떤 부분이 바뀌었는 지

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionally)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Test
- [ ] Documentation
- [ ] Refactoring

### Screenshots (Optional)

### How to test (Optional)
*How to test this PR*

2022-01-06 13:22 UTC, Jeldo requested changes

2022-01-06 13:22 UTC, Jeldo commented on db.py
> +print("DATABASE", DATABASE)
P2: 로깅용으로는 print보다 로깅 모듈을 사용을 권장해드립니다. https://docs.python.org/3/library/logging.html

2022-01-06 13:22 UTC, Jeldo commented on main.py
> +    create_db_and_tables()
P1: EOF, 빈 줄을 추가해주세요.

2022-01-06 13:22 UTC, Jeldo commented on main.py
> +@app.get("/users", response_model=List[UserResponse])
P2: 모든 유저들을 보여주는 API는 불필요해서 삭제해도 좋을 것 같습니다. 생성된 유저를 확인하려면 API로 구현하기보다 DB툴을 사용하거나 직접 CLI로 조회하는 편이 좋습니당.

2022-01-06 13:22 UTC, Jeldo commented on main.py
> +@app.patch("/update/users/{user_id}")
P1: `/users/{user_id}`가 더 적절한 URI입니다. `PATCH`로 갱신하는 API임을 나타내주고 있기 때문에 URL에 update는 없어도 될 것 같습니다.

2022-01-06 13:22 UTC, Jeldo commented on models/models.py
> +    password : str = Field(nullable=False, max_length = 300, regex = "(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}")
P3: 지금은 정규식으로 적용하고 나중에는 이메일/비밀번호 포맷을 검증하는 외부 라이브러리를 사용해서 검증하는 과정을 다른 곳에서 적요하면 좋을 것 같아요.

2022-01-07 00:36 UTC, szto requested changes

2022-01-07 00:36 UTC, szto commented on main.py
> +        db_user = session.exec(select(User).where(User.id == user_id)).one()
ask: 혹시 이렇게 작성할 경우 user 가 db 에 없는 경우는 어떻게 처리가 되나요?

2022-01-07 00:36 UTC, szto commented on main.py
> +            db_user.password = user.password
ask: update api 에서 password 가 없는 경우가 있나요?

2022-01-07 00:36 UTC, szto commented on main.py
> +            db_user.password = user.password
위에 email 도 마찬가지로 혹시 없는 경우가 있는지 한번 확인해 주세요.

2022-01-07 00:36 UTC, szto commented on main.py
> +        return {"message" : "user delete"}
p1: 204 no content 로 에러 내려주시고 빈 데이터로 처리해 주시면 좋겠습니다.

2022-01-07 02:14 UTC, dbwls314 commented on main.py
> +@app.get("/users", response_model=List[UserResponse])
api로 생성하지 않아도 확인할 수 있는 방법이 있기 때문이군요! 감사합니다
수정하였습니다!

2022-01-07 02:20 UTC, dbwls314 commented on main.py
> +@app.patch("/update/users/{user_id}")
넵! 감사합니다! 수정하였습니다!

2022-01-07 02:22 UTC, dbwls314 commented on models/models.py
> +    password : str = Field(nullable=False, max_length = 300, regex = "(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}")
넵! 이메일/ 비밀번호 검증하는 외부 라이브러리 사용방법은 공부하겠습니다! 감사합니다!

2022-01-07 03:53 UTC, dbwls314 commented on main.py
> +    create_db_and_tables()
네! 수정하였습니다!

2022-01-07 04:24 UTC, dbwls314 commented on main.py
> +        return {"message" : "user delete"}
네! 감사합니다 수정했습니다!

2022-01-07 05:18 UTC, dbwls314 commented on main.py
> +        db_user = session.exec(select(User).where(User.id == user_id)).one()
db에 없는 경우의 에러코드 추가로 작성하였습니다!

2022-01-07 05:38 UTC, dbwls314 commented on main.py
> +            db_user.password = user.password
입력받은 user의 email과  password를 동시에 수정하기보단, 둘 중의 한개라도 입력받지 않을 경우라면(email 혹은 passworda 한개만 수정하고 싶은 경우), 이라고 생각하고 작성하게 되었습니다
userupdate model에서 optional 을 이용하여 작성해서 입력받지 않아도 입력받은 정보만 patch 되는것을 확인했습니다.

2022-01-07 05:46 UTC, dbwls314 commented on db.py
> +print("DATABASE", DATABASE)
네 감사합니다!

2022-01-07 21:18 UTC, szto requested changes
.gitignore 에 __pycache__ 추가해서 PR 에서 빼 주세요~

2022-01-10 09:14 UTC, Jeldo requested changes

2022-01-10 09:14 UTC, Jeldo commented on app/main.py
> +        return {"result" : user}
create_user는 회원가입, get_user는 로그인을 위한 API일까요?
회원가입은 POST /api/users/signup
로그인은 POST /api/users/signin
...과 같은 http request method와 path가 적절할 것 같습니다.
회원가입과 로그인은 각각 멱등성을 가지는 요청이기 때문에 POST로 많이 사용하고 있습니다.
쉽게말하면 멱등성을 가진 http request method는 똑같은 요청을 해도 같은 응답을 반환해야합니다.
회원가입은 동일한 요청을 보내면 서버에서는 '이미 존재하는 계정'과 같은 응답을 보내기 때문에 멱등성을 띄지 않습니다.

[멱등성](https://developer.mozilla.org/en-US/docs/Glossary/Idempotent)
[POST](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST)
[POST vs GET for login](https://stackoverflow.com/questions/5868786/what-method-should-i-use-for-a-login-authentication-request)

2022-01-10 09:14 UTC, Jeldo commented on app/main.py
> +            raise HTTPException(status_code = 400, detail = "email exist")
P2: status code를 하드코딩보다는 fastapi.status 에 있는 상수를 사용해주세요. 다른 곳에도 같이 적용해주시면 좋을 것 같습니다.
[Ref](https://fastapi.tiangolo.com/tutorial/response-status-code/#shortcut-to-remember-the-names)

2022-01-10 09:14 UTC, Jeldo commented on app/main.py
> +        user.password = bcrypt.hashpw(user.password.encode('utf-8'), bcrypt.gensalt()).decode()
여기는 이후의 리팩토링에서 비밀번호 해싱하는 함수로 감싸면 좋을 것 같습니다.

2022-01-10 09:14 UTC, Jeldo commented on app/models/models.py
> +    __talename__ = 'trashs'
```suggestion
    __tablename__ = 'trashes'
```

2022-01-10 10:03 UTC, Jeldo requested changes

2022-01-10 10:03 UTC, Jeldo commented on app/main.py
> +        return {}
P1: id에 맞는 유저가 없는 경우에는 404와 함께 알맞은 메세지를 응답으로 반환하고, id에 맞는 유저가 있는 경우에는 해당 유저를 삭제하고 204를 반환합니다. 이 경우에는 별도의 메세지는 작성하지 않아도 좋을 것 같습니다.

2022-01-10 10:03 UTC, Jeldo commented on app/main.py
> +        return {"message" : "create user"}
이후 리팩토링시 커스텀 메세지 포맷을 정의해서 일괄적으로 적용하면 좋을 것 같습니다. 지금은 참고만 해주세요~

2022-01-14 01:53 UTC, dbwls314 commented on app/main.py
> +            raise HTTPException(status_code = 400, detail = "email exist")
네! 적용했습니다.

2022-01-14 01:55 UTC, dbwls314 commented on app/models/models.py
> +    __talename__ = 'trashs'
네! 수정했습니다!

a81c859

2022-01-14 03:37 UTC, dbwls314 commented on app/main.py
> +        user.password = bcrypt.hashpw(user.password.encode('utf-8'), bcrypt.gensalt()).decode()
네! 리팩토링 할때 적용해보도록 하겠습니다!

2022-01-14 04:36 UTC, dbwls314 commented on app/main.py
> +        return {}
네! 수정하였습니다!

295aa5d

2022-01-14 04:47 UTC, dbwls314 commented on app/main.py
> +        return {"result" : user}
수정하였습니다!
 
b66bfd2 -> 추가 : 295aa5d

2022-01-14 04:58 UTC, dbwls314 commented on app/main.py
> +        return {"message" : "create user"}
네 감사합니다! 리팩토링시 적용하도록 하겠습니다!

2022-01-14 07:28 UTC, Jeldo requested changes

2022-01-14 07:28 UTC, Jeldo commented on app/main.py
> +            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail = "user is exist")

```suggestion
            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail = "user already exists")
```

2022-01-14 07:28 UTC, Jeldo commented on app/main.py
> +    return checkpw
P2: 외부로 export 되지 않는 함수들 앞에는 underscore(_)를 붙여주세요. 또한 타입 힌트도 같이 추가해주시면 감사드릴께요.

```suggestion
def _authenticate_user(email: str, password: str) -> Optional[User]:
    with Session(engine) as session:
        user = session.exec(select(User).filter(User.email == email)).first()

    if not user:
        return None
    if not check_password(password, user.password):
        return None
    return user

def _create_access_token(email: str) -> str:
    payload = {"email": email}
    return = jwt.encode(payload, SECRET_KEY, algorithm=ALGORITHM)

def _check_password(password:str, db_password:str) -> bool:
    return bcrypt.checkpw(password.encode('utf-8'), db_password.encode('utf-8'))
```

2022-01-14 07:28 UTC, Jeldo commented on app/models/models.py
> +class UserUpdate(SQLModel):
P2: `UpdateUserRequest`가 조금 더 적절한 이름 일 것 같아요. 사용하는 곳 모두 적용해주세요

2022-01-14 07:28 UTC, Jeldo commented on app/main.py
> +            db_user.password = user.password
P2: pydantic 모델에서 이미 입력필드와 값에 대한 검증을 하고 있어서 조건문은 삭제해도 될 것 같아요.
```suggestion
          db_user.email = user.email
          db_user.password = user.password
```

2022-01-14 07:28 UTC, Jeldo commented on app/main.py
> +        db_user = session.exec(select(User).where(User.id == user_id)).one()
```suggestion
        user = session.exec(select(User).where(User.id == user_id)).one()
```

2022-01-14 08:01 UTC, dbwls314 commented on app/main.py
> +            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail = "user is exist")
네! 수정하였습니다!

2022-01-14 08:04 UTC, dbwls314 commented on app/models/models.py
> +class UserUpdate(SQLModel):
네! 수정하였습니다!

4af77e5

2022-01-14 08:20 UTC, dbwls314 commented on app/main.py
> +            db_user.password = user.password
네! 수정하였습니다!

2022-01-14 08:32 UTC, dbwls314 commented on app/main.py
> +        db_user = session.exec(select(User).where(User.id == user_id)).one()
네 수정하였습니다!

2022-01-14 09:10 UTC, dbwls314 commented on app/main.py
> +    return checkpw
네! 수정하였습니다!

2022-01-14 13:45 UTC, Jeldo approved these changes
파일명 app/models/__inti__.py  -> app/models/__init__.py 수정
코멘트 달아주신 것 해결하시고 머지해주시면 됩니다. 고생하셨어요!

2022-01-14 13:45 UTC, Jeldo commented on app/main.py
> +
EOF; 한 줄 띄워주세요.

2022-01-15 01:34 UTC, szto reviewed
pyc 파일이 아직 지워지지 않은것 같아요. 
https://zzang9ha.tistory.com/359
이렇게 해서 삭제 해 주시면 좋을것 같습니다.

2022-01-15 01:34 UTC, szto commented on app/main.py
> +            headers={"WWW-Authenticate": "Bearer"},
ask 여기 exception 에 header 가 들어가는 이유가 있을까요??

2022-01-15 01:34 UTC, szto commented on app/main.py
> +def update_user(user_id : int, user:UpdateUserRequest) -> dict:
```suggestion
def update_user(user_id : int, user: UpdateUserRequest) -> dict:
```

2022-01-17 01:17 UTC, dbwls314 commented on app/main.py
> +def update_user(user_id : int, user:UpdateUserRequest) -> dict:
넵! 수정하였습니다!

2022-01-17 01:18 UTC, dbwls314 commented on app/main.py
> +
넵! 수정하였습니다!

2022-01-17 01:28 UTC, dbwls314 commented on app/main.py
> +            headers={"WWW-Authenticate": "Bearer"},
이 부분은 공식문서를 참고하여 작성한 에러부분인데, 어떤의도로 작성하였는지는 알고 작성한 부분은 아니였습니다.구글링으로 다시 검색해보니
사용할 수 있는 인증체계(Bearer)를 나타내기 위해 사용하는 것으로 이해하였습니다.

다음에 코드를 작성할 당시에, 어떤 의도를 가지고 사용하는지 한번더 생각하고 작성하도록 하겠습니다!

2022-01-17 01:35 UTC, merged