Feature/account
dbwls314/fastAPI_assign pull request #2
Opened 2022-01-18 06:50 UTC by dbwls314

### Summary

- 요약
  - user 분리
  - user 인가 함수 작성
  - account create 힘수 직성

### Story

- 무엇에 대한 것인지
  - 이전 PR에서 작성한 user의 관심사 분리
  - service단 auth.py - get_crrent_user : user 인가 함수 작성
  - service단 account.py - create_account 함수 작성
  
### Changes

- 어떤 부분이 바뀌었는지
 
### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionally)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Test
- [ ] Documentation
- [ ] Refactoring

### Screenshots (Optional)

### How to test (Optional)
*How to test this PR*

2022-01-18 07:23 UTC, szto requested changes

2022-01-18 07:23 UTC, szto commented on app/api/users.py
> +    result = login_for_access_token(login_request)
여기는 비동시로 사용하시는 이유가 있나요?

2022-01-18 07:23 UTC, szto commented on app/api/users.py
> +
p1: eof 한 줄 추가 부탁드립니다.

2022-01-18 07:23 UTC, szto commented on app/api/users.py
> +    result = update_user(user_id, user)
```suggestion
def patch_user(user_id:str, user_update:UserUpdate):
    result = update_user(user_id=user_id, user_update=user_update)
```
p2: 꼭 파라미터를 명시할 필요가 없긴 한데 저희는 그렇게 사용하고 있어서 맞춰 주시면 좋을것 같아요~

2022-01-18 07:23 UTC, szto commented on app/api/users.py
> +    result = update_user(user_id, user)
다른 코드도 위에 리뷰 처럼 변경해 주시면 좋을것 같습니다~~ user 보다는 좀 더 명확한 변수명이 좋을것 같아서 user_update 같이 해 주시면 좋을것 같습니다.

2022-01-18 07:23 UTC, szto commented on app/service/auth.py
> +    user = _authenticate_user(email=login_request.email, password=login_request.password)
```suggestion
def get_access_token_after_login_success(login_request: LoginRequest) -> dict:
    user = _authenticate_user(email=login_request.email, password=login_request.password)
```
p2: 문법에 맞는지는 조금 헷갈리는데 의미를 좀 더 명확하게 하면 좋을것 같습니다. 생각해 보시고 더 좋은 네이밍을 찾아보셔도 좋을것 같아요.

2022-01-18 07:23 UTC, szto commented on app/service/auth.py
> +    return encoded_jwt
```suggestion
    return jwt.encode(payload, SECRET_KEY, algorithm=ALGORITHM)
```
굳이 변수에 할당 안해 주시는 것이 더 좋을것 같아요. 다른 것도 바꿔주세요~

2022-01-18 07:40 UTC, dbwls314 commented on app/api/users.py
> +
수정하였습니다!

2022-01-18 07:41 UTC, dbwls314 commented on app/api/users.py
> +    result = update_user(user_id, user)
넵! 수정하였습니다!

2022-01-18 07:44 UTC, dbwls314 commented on app/service/auth.py
> +    return encoded_jwt
네! 수정하였습니다!

2022-01-18 08:01 UTC, dbwls314 commented on app/service/auth.py
> +    user = _authenticate_user(email=login_request.email, password=login_request.password)
네! 수정하였습니다!

2022-01-18 08:09 UTC, dbwls314 commented on app/api/users.py
> +    result = login_for_access_token(login_request)
아뇨 없습니다....

2022-01-19 14:19 UTC, Jeldo requested changes

2022-01-19 14:19 UTC, Jeldo commented on app/service/auth.py
> +            user = session.exec(select(User).filter(User.email == token_data.email)).first()
```suggestion
        if email is None:
            raise credentials_exception

        with Session(engine) as session:
            user = session.exec(select(User).filter(User.email == email)).first()
```
P2: TokenData가 불필요한 것 같습니다. 어차피 email 필드만 담는 객체를 생성해서 token_data에 할당하고, 바로 밑에서 token_data.email로 이메일 정보를 가져오고 있어서 굳이 TokenData 클래스에 담아야하는 이유가 없는 것 같습니다.

2022-01-19 14:19 UTC, Jeldo commented on app/service/account.py
> +    account.user_id = token.id
P2: token은 dict형태로 받아오는데, 타입이 str입니다. 타입힌트를 맞추거나 실제 get_current_user의 반환값을 변경해주세요.

2022-01-19 14:19 UTC, Jeldo commented on app/service/auth.py
> +        )
P2: HTTPException은 service보다는 api쪽에 정의하는게 맞습니다. 그리고 별도의 함수로 정의하는게 재사용성, 코드 가독성에 좋습니다. 일단은 함수로 정의하는 것만 하시고, api에서 처리하는 부분은 나중에 진행하면 좋을 것 같습니다. 도원님과 같은 이슈를 겪고 계신 것 같은데 이 문제도 같이 얘기해보세요.

2022-01-20 01:04 UTC, dbwls314 commented on app/service/auth.py
> +            user = session.exec(select(User).filter(User.email == token_data.email)).first()
네! 수정하였습니다!

2022-01-20 01:46 UTC, dbwls314 commented on app/service/account.py
> +    account.user_id = token.id
get_current_user의 반환값이 user의 정보가 dict형태여서, 타입힌트를 `dict`로 수정하였습니다!

2022-01-20 01:54 UTC, dbwls314 commented on app/service/auth.py
> +        )
네!

2022-01-27 04:13 UTC, Jeldo approved these changes

2022-02-01 05:22 UTC, merged